services:
  db:
    image: postgres:15.5-alpine3.18
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - endpoint-pg-data:/var/lib/postgresql/data
      - ./dev-configs/pg_init.sql:/docker-entrypoint-initdb.d/pg_init.sql

volumes:
  endpoint-pg-data:
